#!/bin/bash
#
# Repository Creation Functions
#

# Source utilities if not already loaded
if [ -z "$UTILS_LOADED" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$SCRIPT_DIR/utils.sh"
fi

# Create a GitHub repository
create_github_repo() {
    local org=$1
    local repo=$2
    local description=$3
    local visibility=${4:-private}
    local auto_init=${5:-false}

    print_info "Creating repository $org/$repo..."

    # Check if repo already exists
    if gh api "/repos/$org/$repo" >/dev/null 2>&1; then
        print_warning "Repository $org/$repo already exists"
        return 2
    fi

    # Create repository
    local create_args=(
        "$org/$repo"
        "--${visibility}"
        "--description" "$description"
    )

    if [ "$auto_init" = "true" ]; then
        create_args+=("--add-readme")
    fi

    if gh repo create "${create_args[@]}" 2>&1; then
        print_success "Created repository $org/$repo"
        return 0
    else
        print_error "Failed to create repository $org/$repo"
        return 1
    fi
}

# Initialize repository with initial commit
initialize_repo() {
    local org=$1
    local repo=$2
    local repo_path=$3

    print_info "Initializing repository $org/$repo..."

    cd "$repo_path" || return 1

    # Initialize git if not already
    if [ ! -d ".git" ]; then
        git init
        git branch -M main
    fi

    # Set remote
    local remote_url="https://github.com/$org/$repo.git"
    if git remote get-url origin >/dev/null 2>&1; then
        git remote set-url origin "$remote_url"
    else
        git remote add origin "$remote_url"
    fi

    # Add all files
    git add .

    # Create initial commit if there are changes
    if ! git diff --cached --quiet; then
        git commit -m "Initial commit: Repository scaffolding

Generated by GitHub Infrastructure Setup Script

- Added repository structure
- Added Claude Code configuration
- Added GitHub Actions workflows
- Added documentation

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"

        # Push to GitHub
        print_info "Pushing to GitHub..."
        if git push -u origin main 2>&1; then
            print_success "Pushed to $org/$repo"
            return 0
        else
            print_error "Failed to push to $org/$repo"
            return 1
        fi
    else
        print_info "No changes to commit"
        return 0
    fi
}

# Set repository topics
set_repo_topics() {
    local org=$1
    local repo=$2
    shift 2
    local topics=("$@")

    if [ ${#topics[@]} -eq 0 ]; then
        return 0
    fi

    print_info "Setting topics for $org/$repo..."

    # Convert array to JSON array
    local topics_json=$(printf '%s\n' "${topics[@]}" | jq -R . | jq -s .)

    if gh api "/repos/$org/$repo/topics" -X PUT -f names="$topics_json" >/dev/null 2>&1; then
        print_success "Set topics: ${topics[*]}"
        return 0
    else
        print_warning "Failed to set topics"
        return 1
    fi
}

# Enable branch protection
enable_branch_protection() {
    local org=$1
    local repo=$2
    local branch=${3:-main}

    print_info "Enabling branch protection for $org/$repo:$branch..."

    # Basic branch protection rules
    local protection_json='{
        "required_status_checks": null,
        "enforce_admins": false,
        "required_pull_request_reviews": {
            "required_approving_review_count": 1,
            "dismiss_stale_reviews": true,
            "require_code_owner_reviews": false
        },
        "restrictions": null,
        "required_linear_history": false,
        "allow_force_pushes": false,
        "allow_deletions": false
    }'

    if gh api "/repos/$org/$repo/branches/$branch/protection" \
        -X PUT \
        --input - <<< "$protection_json" >/dev/null 2>&1; then
        print_success "Branch protection enabled"
        return 0
    else
        print_warning "Failed to enable branch protection (may require admin access)"
        return 1
    fi
}

# Add repository to team
add_repo_to_team() {
    local org=$1
    local repo=$2
    local team_slug=$3
    local permission=${4:-push}

    print_info "Adding $org/$repo to team $team_slug..."

    if gh api "/orgs/$org/teams/$team_slug/repos/$org/$repo" \
        -X PUT \
        -f permission="$permission" >/dev/null 2>&1; then
        print_success "Added to team $team_slug with $permission permission"
        return 0
    else
        print_warning "Failed to add to team (team may not exist yet)"
        return 1
    fi
}

# Delete repository (for cleanup/rollback)
delete_github_repo() {
    local org=$1
    local repo=$2

    print_warning "Deleting repository $org/$repo..."

    if gh repo delete "$org/$repo" --yes 2>&1; then
        print_success "Deleted repository $org/$repo"
        return 0
    else
        print_error "Failed to delete repository $org/$repo"
        return 1
    fi
}

# Get repository information
get_repo_info() {
    local org=$1
    local repo=$2

    gh api "/repos/$org/$repo" --jq '{
        name,
        full_name,
        private,
        html_url,
        description,
        default_branch,
        created_at,
        updated_at,
        size,
        stargazers_count,
        watchers_count,
        language,
        has_issues,
        has_projects,
        has_wiki
    }'
}

# Check if repository exists
repo_exists() {
    local org=$1
    local repo=$2

    gh api "/repos/$org/$repo" >/dev/null 2>&1
}

# Export functions
export -f create_github_repo
export -f initialize_repo
export -f set_repo_topics
export -f enable_branch_protection
export -f add_repo_to_team
export -f delete_github_repo
export -f get_repo_info
export -f repo_exists
